from tkinter import *
root=Tk()
miFrame=Frame(root,width=500, height=400)
miFrame.pack()
miImagen=PhotoImage(file="homero.png")
miLabel=Label(miFrame, image=miImagen).place(x=100, y=100)
miLabel2=Label(miFrame, text="Hola", fg="red", font=("comic Sans MS",18)).place(x=250, y=120)
#miLabel.pack()
#miLabel.place(x=100, y=200)
root.mainloop()